### ISSUE TITLE
Doesn't work on Quest

### ISSUE THREAD

**Issue by BattleAxeVR** [PlutoVR/linux-streaming#19]
![image](https://github.com/user-attachments/assets/0916ec65-6e30-4ff7-944a-782e02e85508)

**Comment by rpavlik** [comment]
I think the latest version is over here: https://gitlab.freedesktop.org/monado/electric-maple

though that issue just looks like you need to update the loader version in use.

**Comment by BattleAxeVR** [comment]
That worked, thanks.
